#!/usr/bin/env php
<?php

declare(strict_types=1);

/*
 |----------------------------------------------------------------------
 | Plugs Framework Serve Proxy
 |----------------------------------------------------------------------
 |
 | This script is a thin proxy that delegates to the core `serve` command.
 | It allows you to conveniently run the development server via `php serve`.
 |
 */

$passthroughArgs = array_slice($argv, 1);
$arguments = implode(' ', array_map('escapeshellarg', $passthroughArgs));

$command = "php theplugs serve" . ($arguments ? " {$arguments}" : "");

passthru($command, $status);

exit($status);
