<?php

declare(strict_types=1);

namespace Plugs\Console\Commands;

/*
|--------------------------------------------------------------------------
| Make: Action Command
|--------------------------------------------------------------------------
|
| Creates single-action classes following the Action pattern.
*/

use Plugs\Console\Command;
use Plugs\Console\Support\Str;
use Plugs\Console\Support\Filesystem;

class MakeActionCommand extends Command
{
    protected string $description = 'Create a new action class';

    protected function defineArguments(): array
    {
        return [
            'name' => 'The name of the action class'
        ];
    }

    protected function defineOptions(): array
    {
        return [
            '--model=MODEL' => 'Associated model for the action',
            '--queued' => 'Make the action queueable',
            '--force' => 'Overwrite existing files',
            '--strict' => 'Add strict type declarations',
        ];
    }

    public function handle(): int
    {
        $this->title('Action Generator');

        $name = $this->argument('0');

        if (!$name) {
            $name = $this->ask('Action name', 'CreateUserAction');
        }

        // Ensure it ends with Action
        if (!str_ends_with($name, 'Action')) {
            $name .= 'Action';
        }

        $name = Str::studly($name);

        $options = [
            'model' => $this->option('model'),
            'queued' => $this->hasOption('queued'),
            'force' => $this->isForce(),
            'strict' => $this->hasOption('strict'),
        ];

        // Interactive mode
        if (!$options['model'] && !$this->hasOption('force')) {
            $this->section('Configuration');

            if ($this->confirm('Associate with a model?', false)) {
                $modelName = $this->ask('Model name');
                $options['model'] = Str::studly($modelName);
            }

            $options['queued'] = $this->confirm('Make action queueable?', false);
        }

        $path = $this->getActionPath($name);

        if (Filesystem::exists($path) && !$options['force']) {
            if (!$this->confirm("Action {$name} already exists. Overwrite?", false)) {
                $this->warning('Action generation cancelled.');
                return 0;
            }
        }

        $this->section('Generating Files');

        $this->task('Creating action class', function () use ($name, $options, $path) {
            $content = $this->generateActionClass($name, $options);
            Filesystem::put($path, $content);
            usleep(200000);
        });

        $this->success("Action created: {$path}");

        $this->newLine(2);
        $this->box(
            "Action '{$name}' generated successfully!\n\n" .
            "Path: app/Actions/{$name}.php",
            "✅ Success",
            "success"
        );

        return 0;
    }

    private function getActionPath(string $name): string
    {
        return getcwd() . '/app/Actions/' . $name . '.php';
    }

    private function generateActionClass(string $name, array $options): string
    {
        $strict = $options['strict'] ? "declare(strict_types=1);\n\n" : '';
        $imports = $this->buildImports($options);
        $traits = $options['queued'] ? "\n    use Queueable;\n" : '';
        $properties = $this->buildProperties($options);
        $methods = $this->buildMethods($options);

        return <<<PHP
<?php

{$strict}namespace App\Actions;

{$imports}

/**
 * {$name}
 *
 * Single-action class following the Action pattern.
 * Actions encapsulate a single piece of business logic.
 * 
 * Generated by ThePlugs Console
 */
class {$name}
{{$traits}
{$properties}
{$methods}
}

PHP;
    }

    private function buildImports(array $options): string
    {
        $imports = [];

        if ($options['model']) {
            $imports[] = "use App\\Models\\{$options['model']};";
        }

        return implode("\n", $imports);
    }

    private function buildProperties(array $options): string
    {
        return '';
    }

    private function buildMethods(array $options): string
    {
        $model = $options['model'];
        $returnType = $model ? "?{$model}" : 'mixed';
        $paramType = $model ? "{$model} \$" . Str::camel($model) : 'array $data';

        $body = $model
            ? "// Implement action logic for {$model}\n        return null;"
            : "// Implement action logic\n        return null;";

        return <<<PHP
    /**
     * Execute the action
     *
     * This is the main entry point for the action.
     * All business logic should be implemented here.
     *
     * @param {$paramType}
     * @return {$returnType}
     */
    public function __invoke({$paramType}): {$returnType}
    {
        {$body}
    }

    /**
     * Execute the action (alternative method name)
     */
    public function handle({$paramType}): {$returnType}
    {
        return \$this->__invoke({$paramType});
    }
PHP;
    }
}
