<?php

declare(strict_types=1);

namespace Plugs\Console\Commands;

/*
|--------------------------------------------------------------------------
| Make: Enum Command
|--------------------------------------------------------------------------
|
| Creates PHP 8.1+ enum classes.
*/

use Plugs\Console\Command;
use Plugs\Console\Support\Filesystem;
use Plugs\Console\Support\Str;

class MakeEnumCommand extends Command
{
    protected string $description = 'Create a new enum class';

    protected function defineArguments(): array
    {
        return [
            'name' => 'The name of the enum class',
        ];
    }

    protected function defineOptions(): array
    {
        return [
            '--backed=TYPE' => 'Make the enum backed by a type (string, int)',
            '--force' => 'Overwrite existing files',
        ];
    }

    public function handle(): int
    {
        $this->checkpoint('start');
        $this->title('Enum Generator');

        $name = $this->argument('0');

        if (!$name) {
            $name = $this->ask('Enum name', 'Status');
        }

        $name = Str::studly($name);

        $options = [
            'backed' => $this->option('backed'),
            'force' => $this->isForce(),
        ];

        // Interactive mode
        if (!$options['backed'] && !$this->hasOption('force')) {
            $this->section('Configuration');

            if ($this->confirm('Should this be a backed enum?', false)) {
                $options['backed'] = $this->choice('Type', ['string', 'int'], 'string');
            }
        }

        $path = $this->getEnumPath($name);

        $this->section('Configuration Summary');
        $this->keyValue('Enum Name', $name);
        $this->keyValue('Backed Type', $options['backed'] ?: 'None');
        $this->keyValue('Target Path', str_replace(getcwd() . DIRECTORY_SEPARATOR, '', $path));
        $this->newLine();

        if (Filesystem::exists($path) && !$options['force']) {
            if (!$this->confirm("Enum {$name} already exists. Overwrite?", false)) {
                $this->warning('Enum generation cancelled.');

                return 0;
            }
        }

        $this->checkpoint('generating');

        $this->task('Creating enum class', function () use ($name, $options, $path) {
            $content = $this->generateEnumClass($name, $options);
            Filesystem::put($path, $content);
            usleep(200000);
        });

        $this->checkpoint('finished');

        $this->newLine(2);
        $this->box(
            "Enum '{$name}' generated successfully!\n\n" .
            "Time: {$this->formatTime($this->elapsed())}",
            "✅ Success",
            "success"
        );

        if ($this->isVerbose()) {
            $this->displayTimings();
        }

        return 0;
    }

    private function getEnumPath(string $name): string
    {
        return getcwd() . '/app/Enums/' . $name . '.php';
    }

    private function generateEnumClass(string $name, array $options): string
    {
        $backed = $options['backed'] ? ": {$options['backed']}" : '';
        $cases = $options['backed']
            ? "    case ACTIVE = 'active';\n    case INACTIVE = 'inactive';"
            : "    case ACTIVE;\n    case INACTIVE;";

        return <<<PHP
<?php

declare(strict_types=1);

namespace App\Enums;

/**
 * {$name}
 *
 * Generated by ThePlugs Console
 */
enum {$name}{$backed}
{
{$cases}
}

PHP;
    }
}
