<?php

declare(strict_types=1);

namespace Plugs\Console\Commands;

/*
|--------------------------------------------------------------------------
| Make: Resource Command
|--------------------------------------------------------------------------
|
| Creates API Resource classes for transforming data.
*/

use Plugs\Console\Command;
use Plugs\Console\Support\Filesystem;
use Plugs\Console\Support\Str;

class MakeResourceCommand extends Command
{
    protected string $description = 'Create a new API resource class';

    protected function defineArguments(): array
    {
        return [
            'name' => 'The name of the resource class',
        ];
    }

    protected function defineOptions(): array
    {
        return [
            '--model=MODEL' => 'Associated model for the resource',
            '--collection' => 'Generate a resource collection',
            '--force' => 'Overwrite existing files',
            '--strict' => 'Add strict type declarations',
        ];
    }

    public function handle(): int
    {
        $this->title('API Resource Generator');

        $name = $this->argument('0');

        if (!$name) {
            $name = $this->ask('Resource name', 'UserResource');
        }

        // Ensure it ends with Resource
        if (!str_ends_with($name, 'Resource') && !str_ends_with($name, 'Collection')) {
            $name .= 'Resource';
        }

        $name = Str::studly($name);

        $options = [
            'model' => $this->option('model'),
            'collection' => $this->hasOption('collection'),
            'force' => $this->isForce(),
            'strict' => $this->hasOption('strict'),
        ];

        // Interactive mode
        if (!$options['model'] && !$this->hasOption('force')) {
            $this->section('Configuration');

            if ($this->confirm('Associate with a model?', true)) {
                $modelName = $this->ask('Model name', str_replace(['Resource', 'Collection'], '', $name));
                $options['model'] = Str::studly($modelName);
            }

            $options['collection'] = $this->confirm('Generate collection resource too?', false);
        }

        $path = $this->getResourcePath($name);

        if (Filesystem::exists($path) && !$options['force']) {
            if (!$this->confirm("Resource {$name} already exists. Overwrite?", false)) {
                $this->warning('Resource generation cancelled.');

                return 0;
            }
        }

        $this->section('Generating Files');
        $filesCreated = [];

        // Generate main resource
        $this->task('Creating resource class', function () use ($name, $options, $path) {
            $content = $this->generateResourceClass($name, $options);
            Filesystem::put($path, $content);
            usleep(200000);
        });

        $filesCreated[] = $path;
        $this->success("Resource created: {$path}");

        // Generate collection if requested
        if ($options['collection']) {
            $collectionName = str_replace('Resource', 'Collection', $name);
            $collectionPath = $this->getResourcePath($collectionName);

            $this->task('Creating collection class', function () use ($collectionName, $name, $options, $collectionPath) {
                $content = $this->generateCollectionClass($collectionName, $name, $options);
                Filesystem::put($collectionPath, $content);
                usleep(150000);
            });

            $filesCreated[] = $collectionPath;
            $this->success("Collection created: {$collectionPath}");
        }

        $this->newLine(2);
        $this->box(
            "Resource '{$name}' generated successfully!\n\n" .
            "Files created: " . count($filesCreated),
            "✅ Success",
            "success"
        );

        return 0;
    }

    private function getResourcePath(string $name): string
    {
        return getcwd() . '/app/Http/Resources/' . $name . '.php';
    }

    private function generateResourceClass(string $name, array $options): string
    {
        $strict = $options['strict'] ? "declare(strict_types=1);\n\n" : '';
        $model = $options['model'] ?? 'Model';

        return <<<PHP
<?php

{$strict}namespace App\Http\Resources;

use Plugs\Http\Resources\PlugResource;

/**
 * {$name}
 *
 * API Resource for transforming {$model} data.
 * Generated by ThePlugs Console
 * 
 * @property mixed \$resource The underlying {$model} instance
 */
class {$name} extends PlugResource
{
    /**
     * Transform the resource into an array.
     * 
     * Use \$this->resource to access the underlying model/data.
     * 
     * Available helpers:
     *   - \$this->when(\$condition, \$value, \$default) - Conditional attributes
     *   - \$this->whenLoaded('relation') - Include only when relation is loaded
     *   - \$this->whenNotNull(\$value) - Include only when value is not null
     *   - \$this->mergeWhen(\$condition, \$values) - Conditionally merge arrays
     */
    public function toArray(): array
    {
        return [
            'id' => \$this->resource->id,
            // 'name' => \$this->resource->name,
            // 'email' => \$this->resource->email,
            
            // Conditional attribute example:
            // 'is_admin' => \$this->when(\$this->resource->is_admin, true),
            
            // Include relationship only when loaded:
            // 'posts' => \$this->whenLoaded('posts', function(\$posts) {
            //     return PostResource::collection(\$posts);
            // }),
            
            // Include only when not null:
            // 'avatar' => \$this->whenNotNull(\$this->resource->avatar_url),
            
            // Timestamps
            'created_at' => \$this->resource->created_at,
            'updated_at' => \$this->resource->updated_at,
        ];
    }
}

PHP;
    }

    private function generateCollectionClass(string $collectionName, string $resourceName, array $options): string
    {
        $strict = $options['strict'] ? "declare(strict_types=1);\n\n" : '';

        return <<<PHP
<?php

{$strict}namespace App\Http\Resources;

use Plugs\Http\Resources\PlugResourceCollection;

/**
 * {$collectionName}
 *
 * API Resource Collection for transforming multiple {$resourceName} items.
 * Generated by ThePlugs Console
 */
class {$collectionName} extends PlugResourceCollection
{
    /**
     * The resource class this collection uses
     */
    protected string \$collects = {$resourceName}::class;

    /**
     * Transform the collection into an array.
     * 
     * Override this method to customize the collection output.
     * By default, uses the parent toArray() which transforms each item.
     */
    // public function toArray(): array
    // {
    //     return parent::toArray();
    // }
}

PHP;
    }
}
