<?php

declare(strict_types=1);

namespace Plugs\Console\Commands;

/*
|--------------------------------------------------------------------------
| Make: Resource Command
|--------------------------------------------------------------------------
|
| Creates API Resource classes for transforming data.
*/

use Plugs\Console\Command;
use Plugs\Console\Support\Filesystem;
use Plugs\Console\Support\Str;

class MakeResourceCommand extends Command
{
    protected string $description = 'Create a new API resource class';

    protected function defineArguments(): array
    {
        return [
            'name' => 'The name of the resource class',
        ];
    }

    protected function defineOptions(): array
    {
        return [
            '--model=MODEL' => 'Associated model for the resource',
            '--collection' => 'Generate a resource collection',
            '--force' => 'Overwrite existing files',
            '--strict' => 'Add strict type declarations',
        ];
    }

    public function handle(): int
    {
        $this->title('API Resource Generator');

        $name = $this->argument('0');

        if (!$name) {
            $name = $this->ask('Resource name', 'UserResource');
        }

        // Ensure it ends with Resource
        if (!str_ends_with($name, 'Resource') && !str_ends_with($name, 'Collection')) {
            $name .= 'Resource';
        }

        $name = Str::studly($name);

        $options = [
            'model' => $this->option('model'),
            'collection' => $this->hasOption('collection'),
            'force' => $this->isForce(),
            'strict' => $this->hasOption('strict'),
        ];

        // Interactive mode
        if (!$options['model'] && !$this->hasOption('force')) {
            $this->section('Configuration');

            if ($this->confirm('Associate with a model?', true)) {
                $modelName = $this->ask('Model name', str_replace(['Resource', 'Collection'], '', $name));
                $options['model'] = Str::studly($modelName);
            }

            $options['collection'] = $this->confirm('Generate collection resource too?', false);
        }

        $path = $this->getResourcePath($name);

        if (Filesystem::exists($path) && !$options['force']) {
            if (!$this->confirm("Resource {$name} already exists. Overwrite?", false)) {
                $this->warning('Resource generation cancelled.');

                return 0;
            }
        }

        $this->section('Generating Files');
        $filesCreated = [];

        // Generate main resource
        $this->task('Creating resource class', function () use ($name, $options, $path) {
            $content = $this->generateResourceClass($name, $options);
            Filesystem::put($path, $content);
            usleep(200000);
        });

        $filesCreated[] = $path;
        $this->success("Resource created: {$path}");

        // Generate collection if requested
        if ($options['collection']) {
            $collectionName = str_replace('Resource', 'Collection', $name);
            $collectionPath = $this->getResourcePath($collectionName);

            $this->task('Creating collection class', function () use ($collectionName, $name, $options, $collectionPath) {
                $content = $this->generateCollectionClass($collectionName, $name, $options);
                Filesystem::put($collectionPath, $content);
                usleep(150000);
            });

            $filesCreated[] = $collectionPath;
            $this->success("Collection created: {$collectionPath}");
        }

        $this->newLine(2);
        $this->box(
            "Resource '{$name}' generated successfully!\n\n" .
            "Files created: " . count($filesCreated),
            "✅ Success",
            "success"
        );

        return 0;
    }

    private function getResourcePath(string $name): string
    {
        return getcwd() . '/app/Http/Resources/' . $name . '.php';
    }

    private function generateResourceClass(string $name, array $options): string
    {
        $strict = $options['strict'] ? "declare(strict_types=1);\n\n" : '';
        $model = $options['model'] ?? 'Model';
        $modelVar = Str::camel($model);

        return <<<PHP
<?php

{$strict}namespace App\Http\Resources;

/**
 * {$name}
 *
 * API Resource for transforming {$model} data.
 * Generated by ThePlugs Console
 */
class {$name}
{
    protected mixed \$resource;

    public function __construct(mixed \$resource)
    {
        \$this->resource = \$resource;
    }

    /**
     * Transform the resource into an array
     */
    public function toArray(): array
    {
        // If resource is an array, return it with transformations
        if (is_array(\$this->resource)) {
            return [
                'id' => \$this->resource['id'] ?? null,
                // Add more transformations here
            ];
        }

        // If resource is an object (model)
        return [
            'id' => \$this->resource->id ?? null,
            // Add more transformations here
            // 'name' => \$this->resource->name,
            // 'email' => \$this->resource->email,
            // 'created_at' => \$this->resource->created_at?->toIso8601String(),
        ];
    }

    /**
     * Create a collection of resources
     */
    public static function collection(array \$resources): array
    {
        return array_map(fn(\$resource) => (new static(\$resource))->toArray(), \$resources);
    }

    /**
     * Convert to JSON response format
     */
    public function toResponse(): array
    {
        return [
            'data' => \$this->toArray(),
        ];
    }

    /**
     * Add additional data to the response
     */
    public function additional(array \$data): array
    {
        return array_merge(\$this->toResponse(), \$data);
    }
}

PHP;
    }

    private function generateCollectionClass(string $collectionName, string $resourceName, array $options): string
    {
        $strict = $options['strict'] ? "declare(strict_types=1);\n\n" : '';

        return <<<PHP
<?php

{$strict}namespace App\Http\Resources;

/**
 * {$collectionName}
 *
 * API Resource Collection for transforming multiple resources.
 * Generated by ThePlugs Console
 */
class {$collectionName}
{
    protected array \$resources;
    protected array \$meta = [];

    public function __construct(array \$resources)
    {
        \$this->resources = \$resources;
    }

    /**
     * Transform the resource collection into an array
     */
    public function toArray(): array
    {
        return array_map(
            fn(\$resource) => (new {$resourceName}(\$resource))->toArray(),
            \$this->resources
        );
    }

    /**
     * Add meta data to the collection
     */
    public function withMeta(array \$meta): self
    {
        \$this->meta = array_merge(\$this->meta, \$meta);
        return \$this;
    }

    /**
     * Convert to JSON response format
     */
    public function toResponse(): array
    {
        \$response = [
            'data' => \$this->toArray(),
        ];

        if (!empty(\$this->meta)) {
            \$response['meta'] = \$this->meta;
        }

        return \$response;
    }

    /**
     * Add pagination data
     */
    public function withPagination(int \$total, int \$perPage, int \$currentPage): self
    {
        return \$this->withMeta([
            'total' => \$total,
            'per_page' => \$perPage,
            'current_page' => \$currentPage,
            'last_page' => (int) ceil(\$total / \$perPage),
        ]);
    }
}

PHP;
    }
}
