<?php

declare(strict_types=1);

namespace Plugs\Console\Commands;

/*
|--------------------------------------------------------------------------
| Make: DTO Command
|--------------------------------------------------------------------------
|
| Creates Data Transfer Object classes.
*/

use Plugs\Console\Command;
use Plugs\Console\Support\Filesystem;
use Plugs\Console\Support\Str;

class MakeDTOCommand extends Command
{
    protected string $description = 'Create a new Data Transfer Object class';

    protected function defineArguments(): array
    {
        return [
            'name' => 'The name of the DTO class',
        ];
    }

    protected function defineOptions(): array
    {
        return [
            '--properties=PROPS' => 'Comma-separated list of properties',
            '--from-model=MODEL' => 'Generate DTO from model properties',
            '--immutable' => 'Make the DTO immutable (readonly)',
            '--force' => 'Overwrite existing files',
            '--strict' => 'Add strict type declarations',
        ];
    }

    public function handle(): int
    {
        $this->checkpoint('start');
        $this->title('DTO Generator');

        $name = $this->argument('0');

        if (!$name) {
            $name = $this->ask('DTO name', 'UserData');
        }

        if (!str_ends_with($name, 'Data') && !str_ends_with($name, 'DTO')) {
            $name .= 'Data';
        }

        $name = Str::studly($name);

        $options = [
            'properties' => $this->option('properties'),
            'from_model' => $this->option('from-model'),
            'immutable' => $this->hasOption('immutable'),
            'force' => $this->isForce(),
            'strict' => $this->hasOption('strict'),
        ];

        // Interactive mode
        if (!$options['properties'] && !$options['from_model'] && !$this->hasOption('force')) {
            $this->section('Configuration');

            $propsInput = $this->ask('Properties (comma-separated, format: name:type)', 'id:int,name:string,email:string');
            $options['properties'] = $propsInput;

            $options['immutable'] = $this->confirm('Make DTO immutable (readonly)?', true);
        }

        $path = $this->getDTOPath($name);

        $this->section('Configuration Summary');
        $this->keyValue('DTO Name', $name);
        $this->keyValue('Immutable', $options['immutable'] ? 'Yes' : 'No');
        $this->keyValue('Properties', $options['properties'] ?: 'Default');
        $this->keyValue('Target Path', str_replace(getcwd() . '/', '', $path));
        $this->newLine();

        if (Filesystem::exists($path) && !$options['force']) {
            if (!$this->confirm("DTO {$name} already exists. Overwrite?", false)) {
                $this->warning('DTO generation cancelled.');
                return 0;
            }
        }

        $this->checkpoint('generating');

        $this->task('Creating DTO class', function () use ($name, $options, $path) {
            $content = $this->generateDTOClass($name, $options);
            Filesystem::put($path, $content);
            usleep(200000);
        });

        $this->checkpoint('finished');

        $this->newLine(2);
        $this->box(
            "DTO '{$name}' generated successfully!\n\n" .
            "Time: {$this->formatTime($this->elapsed())}",
            "✅ Success",
            "success"
        );

        if ($this->isVerbose()) {
            $this->displayTimings();
        }

        return 0;
    }

    private function getDTOPath(string $name): string
    {
        return getcwd() . '/app/DTOs/' . $name . '.php';
    }

    private function generateDTOClass(string $name, array $options): string
    {
        $strict = $options['strict'] ? "declare(strict_types=1);\n\n" : '';
        $properties = $this->parseProperties($options['properties'] ?? 'id:int,name:string');
        $readonly = $options['immutable'] ? 'readonly ' : '';

        $propsString = $this->buildProperties($properties, $options['immutable']);
        $constructor = $this->buildConstructor($properties, $options['immutable']);
        $methods = $this->buildMethods($properties, $name);

        return <<<PHP
<?php

{$strict}namespace App\DTOs;

/**
 * {$name}
 *
 * Data Transfer Object for transferring data between layers.
 * Generated by ThePlugs Console
 */
{$readonly}class {$name}
{
{$propsString}
{$constructor}
{$methods}
}

PHP;
    }

    private function parseProperties(?string $properties): array
    {
        if (!$properties) {
            return [];
        }

        $parsed = [];
        $props = array_map('trim', explode(',', $properties));

        foreach ($props as $prop) {
            if (str_contains($prop, ':')) {
                [$name, $type] = explode(':', $prop, 2);
                $parsed[trim($name)] = trim($type);
            } else {
                $parsed[trim($prop)] = 'mixed';
            }
        }

        return $parsed;
    }

    private function buildProperties(array $properties, bool $immutable): string
    {
        if (empty($properties)) {
            return '';
        }

        $props = [];
        foreach ($properties as $name => $type) {
            $readonly = $immutable ? '' : ''; // readonly on class level in PHP 8.2+
            $props[] = "    public {$type} \${$name};";
        }

        return implode("\n", $props);
    }

    private function buildConstructor(array $properties, bool $immutable): string
    {
        if (empty($properties)) {
            return '';
        }

        $params = [];
        $assignments = [];

        foreach ($properties as $name => $type) {
            $params[] = "        {$type} \${$name}";
            $assignments[] = "        \$this->{$name} = \${$name};";
        }

        $paramStr = implode(",\n", $params);
        $assignStr = implode("\n", $assignments);

        return <<<PHP

    public function __construct(
{$paramStr}
    ) {
{$assignStr}
    }
PHP;
    }

    private function buildMethods(array $properties, string $className): string
    {
        $methods = [];

        // fromArray factory method
        $fromArrayAssignments = [];
        foreach ($properties as $name => $type) {
            $fromArrayAssignments[] = "            \$data['{$name}'] ?? null";
        }
        $fromArrayStr = implode(",\n", $fromArrayAssignments);

        $methods[] = <<<PHP

    /**
     * Create DTO from array
     */
    public static function fromArray(array \$data): self
    {
        return new self(
{$fromArrayStr}
        );
    }
PHP;

        // toArray method
        $toArrayAssignments = [];
        foreach ($properties as $name => $type) {
            $toArrayAssignments[] = "            '{$name}' => \$this->{$name}";
        }
        $toArrayStr = implode(",\n", $toArrayAssignments);

        $methods[] = <<<PHP

    /**
     * Convert DTO to array
     */
    public function toArray(): array
    {
        return [
{$toArrayStr}
        ];
    }
PHP;

        return implode("\n", $methods);
    }
}
