<?php

declare(strict_types=1);

namespace Plugs\Console\Commands;

/*
|--------------------------------------------------------------------------
| Make: Request Command
|--------------------------------------------------------------------------
|
| Creates form request classes for validation and authorization.
*/

use Plugs\Console\Command;
use Plugs\Console\Support\Filesystem;
use Plugs\Console\Support\Str;

class MakeRequestCommand extends Command
{
    protected string $description = 'Create a new form request class';

    protected function defineArguments(): array
    {
        return [
            'name' => 'The name of the request class',
        ];
    }

    protected function defineOptions(): array
    {
        return [
            '--rules=RULES' => 'Comma-separated list of fields to validate',
            '--auth' => 'Add authorization logic',
            '--force' => 'Overwrite existing files',
            '--strict' => 'Add strict type declarations',
        ];
    }

    public function handle(): int
    {
        $this->checkpoint('start');
        $this->title('Form Request Generator');

        $name = $this->argument('0');

        if (!$name) {
            $name = $this->ask('Request name', 'StoreUserRequest');
        }

        if (!str_ends_with($name, 'Request')) {
            $name .= 'Request';
        }

        $name = Str::studly($name);

        $options = [
            'rules' => $this->option('rules'),
            'auth' => $this->hasOption('auth'),
            'force' => $this->isForce(),
            'strict' => $this->hasOption('strict'),
        ];

        // Interactive mode if no rules provided
        if (!$options['rules'] && !$this->hasOption('force')) {
            $this->section('Configuration');

            $rulesInput = $this->ask('Fields to validate (comma-separated)', 'name,email');
            $options['rules'] = $rulesInput;

            $options['auth'] = $this->confirm('Add authorization method?', false);
        }

        $path = $this->getRequestPath($name);

        $this->section('Configuration Summary');
        $this->keyValue('Request Name', $name);
        $this->keyValue('Auth Method', $options['auth'] ? 'Yes' : 'No');
        $this->keyValue('Rule Fields', $options['rules'] ?: 'Default');
        $this->keyValue('Target Path', str_replace(getcwd() . '/', '', $path));
        $this->newLine();

        if (Filesystem::exists($path) && !$options['force']) {
            if (!$this->confirm("Request {$name} already exists. Overwrite?", false)) {
                $this->warning('Request generation cancelled.');

                return 0;
            }
        }

        $this->checkpoint('generating');

        $this->task('Creating form request class', function () use ($name, $options, $path) {
            $content = $this->generateRequestClass($name, $options);
            Filesystem::put($path, $content);
            usleep(200000);
        });

        $this->checkpoint('finished');

        $this->newLine(2);
        $this->box(
            "Form Request '{$name}' generated successfully!\n\n" .
            "Time: {$this->formatTime($this->elapsed())}",
            "✅ Success",
            "success"
        );

        if ($this->isVerbose()) {
            $this->displayTimings();
        }

        return 0;
    }

    private function getRequestPath(string $name): string
    {
        return getcwd() . '/app/Http/Requests/' . $name . '.php';
    }

    private function generateRequestClass(string $name, array $options): string
    {
        $strict = $options['strict'] ? "declare(strict_types=1);\n\n" : '';
        $rules = $this->buildRules($options['rules']);
        $authorize = $this->buildAuthorize($options['auth']);

        return <<<PHP
<?php

{$strict}namespace App\Http\Requests;

use Plugs\Http\Requests\FormRequest;

/**
 * {$name}
 *
 * Form request for handling validation and authorization.
 * Generated by ThePlugs Console
 */
class {$name} extends FormRequest
{
{$authorize}

    /**
     * Get validation rules
     */
    public function rules(): array
    {
        return {$rules};
    }

    /**
     * Get custom validation messages
     */
    public function messages(): array
    {
        return [
            // Define custom messages here
        ];
    }

    /**
     * Get custom attribute names
     */
    public function attributes(): array
    {
        return [
            // Define custom attribute names here
        ];
    }

    /**
     * Get the sanitization rules that apply to the request.
     */
    public function sanitizers(): array
    {
        return [
            // Define sanitization rules here
            // Example: 'email' => 'email', 'name' => 'string'
        ];
    }
}

PHP;
    }

    private function buildRules(?string $rules): string
    {
        if (!$rules) {
            return "[\n            // Add validation rules here\n        ]";
        }

        $fields = array_map('trim', explode(',', $rules));
        $rulesArray = [];

        foreach ($fields as $field) {
            $rulesArray[] = "            '{$field}' => 'required',";
        }

        return "[\n" . implode("\n", $rulesArray) . "\n        ]";
    }

    private function buildAuthorize(bool $withLogic): string
    {
        $body = $withLogic ? "// Add authorization logic here\n        // Example: return auth()->check();\n        return true;" : 'return true;';

        return <<<PHP
    /**
     * Determine if the user is authorized to make this request
     */
    public function authorize(): bool
    {
        {$body}
    }
PHP;
    }
}
